version: '3.8'

services:
  server:
    build: ./server
    container_name: yellowshield-backend
    ports:
      - "5001:5001"
    volumes:
      - ./server/database.sqlite:/app/database.sqlite
      - ./server/data:/app/data
    environment:
      - PORT=5000
      - JWT_SECRET=secret
    restart: unless-stopped

  client:
    build: ./client
    container_name: yellowshield-frontend
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
